name: glitty
description: "Car Wash Booking and Payment App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_bloc: ^8.1.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  dio: ^5.4.3+1
  file_picker: ^8.0.5
  mime: ^1.0.5
  flutter_stripe: ^12.1.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.3.0
  flutter_svg: ^2.0.9
  geolocator: ^11.0.0
  url_launcher: ^6.1.11
  image_picker: ^1.0.4
  overlay_support: 2.1.0
  firebase_core: ^2.24.1
  firebase_messaging: ^14.7.1
  google_sign_in: ^6.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6 # For code generation
  mockito: ^5.4.2 # For testing
  flutter_launcher_icons: ^0.13.1 # For app icons


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding.svg
    #- assets/icons/
    #- assets/animations/
    #- assets/translations/
